### ISSUE TITLE
SSL letsencrypt integration

### ISSUE THREAD

**Issue by joemewes** [4AllDigital/DruDockCli#194]
Integrate lets encrypt with prod setup

```
version: "3"

services:
  nginx-proxy:
    image: 4alldigital/drudock-nginx-proxy:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/proxy/certs:/etc/nginx/certs:ro
      - ./config/proxy/vhost.d:/etc/nginx/vhost.d
      - ./config/proxy/html:/usr/share/nginx/html
    hostname: nginx-proxy
    networks:
      - drudock-frontend
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/proxy/certs:/etc/nginx/certs:rw
      - ./config/proxy/vhost.d:/etc/nginx/vhost.d
      - ./config/proxy/html:/usr/share/nginx/html
    networks:
      - drudock-frontend

networks:
  drudock-frontend:
    driver: bridge
```

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
